name: Validate code in the merge queue (post merge)

on:
  merge_group:

jobs:
  post-merge-queue:
    name: Ready for mergequeue
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo ${{ github.event.merge_group.base_ref  }}
