name: Monorepo pipeline - build and deploy

on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'pre-release/**'
  workflow_dispatch:
  create:


defaults:
  run:
    shell: bash

# env:
#   DOCKER_REGISTRY: some-registry
#   DOCKER_BASE_IMAGE_REGISTRY: some-base-registry
#   SPINNAKER_URL: www.some-spinnaker-url.com
#   COMPOSE_HTTP_TIMEOUT: 180
#   NX_AFFECTED_ALL: ${{ contains(github.event.pull_request.labels.*.name, 'nx-affected-all') }}

jobs:
  debug:
    name: Dump Github context
    runs-on: ubunutu-runners
    env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Get git branch
        run: |
          node --version


