name: Monorepo pipeline - build and deploy

on:
  push: {}
  workflow_dispatch:
  create:


defaults:
  run:
    shell: bash

env:
  DOCKER_REGISTRY: some-registry

jobs:
  debug:
    name: Dump Github context
    runs-on: ubuntu-latest
    env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Get git branch
        run: |
          echo "Asserting that merge queue actually pushes to main"
          echo $SLACK_BOT_TOKEN


      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel:  ${{ secrets.SLACK_CHANNEL_ID }}
            text: "howdy <@channel>!"
